title: C ile Görüntü İşleme Uygulamaları
email: abacibahri@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  IMLAB.io, C dilinde yazılmış IMLAB kütüphanesi ile Görüntü İşleme, Makine Öğrenmesi ve Bilgisayarlı Görü alanında 
  yayınlanmış algoritmaların incelendiği, bu alanda çalışma yapmak isteyenler için temel konuların anlatıldığı blog sayfasıdır.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.imlab.io"
github_username:  cescript

# plainwhite settings
plainwhite:
  name: Bahri ABACI
  tagline: Developer. Engineer.
  date_format: "%b %-d, %Y"

  analytics_id: UA-31519600-1

  social_links:
    github:  cescript
    linkedIn: in/abacibahri/
    reddit: user/cescript

# preview post content
show_excerpts: true
excerpt_separator: "<!--more-->"
sitemap: true # set to true to generate sitemap.xml content

# set the url style
permalink: /:year/:month/:day/:title/

# set the plugins
plugins:
  - jekyll-seo-tag

kramdown:
  input: GFM